subprojects {
    apply plugin: 'java'
    def tickloomVersion = '0.1.0-alpha.30'
    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    repositories {
        mavenLocal()
        mavenCentral()
        maven { url 'https://repo.clojars.org/' }
    }

    dependencies {
        testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
        implementation "io.github.unmeshjoshi:tickloom:${tickloomVersion}"
        testImplementation "io.github.unmeshjoshi:tickloom-testkit:${tickloomVersion}"
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
    }
}
